### ISSUE TITLE
Bug: 502 Bad gateway

### ISSUE THREAD

**Issue by KrazyKleb** [diced/zipline#529]
### What happened?

How am I supposed to set up my domain? When I use a proxy it says "502 Bad gateway", so what sort of dns settings should I use for my custom domain?

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
There are no logs when the error happens
```

**Comment by wraithy** [comment]
What reverse proxy are you using? If you are using Nginx, post your config so that we can see if there are any issues with it. Make sure that your Zipline instance is running correctly (you can do this using `docker ps` if you are using Docker) and that there are no issues from the console (you can check the logs in Docker using `docker logs zipline-zipline-1`).

**Comment by KrazyKleb** [comment]
> What reverse proxy are you using? If you are using Nginx, post your config so that we can see if there are any issues with it. Make sure that your Zipline instance is running correctly (you can do this using `docker ps` if you are using Docker) and that there are no issues from the console (you can check the logs in Docker using `docker logs zipline-zipline-1`). 

I'm using the proxy that my host uses, so I don't have config.
The host uses pterodactyl, so I don't have docker logs

I was just wondering if I should use an A record pointing to my server

**Comment by KrazyKleb** [comment]
Update: I used an A record and it still says bad gateway

**Comment by wraithy** [comment]
You do need an A record pointing to server that is hosting Zipline yes however it sounds like your issue has something to do with the reverse proxy. Since you don't have access to the reverse proxy config or the Zipline logs, I can't offer much help. If you have access to the containers in the Pterodactyl panel, you may be able to find some info there but other than that I don't know what to suggest.

**Comment by KrazyKleb** [comment]
> You do need an A record pointing to server that is hosting Zipline yes however it sounds like your issue has something to do with the reverse proxy. Since you don't have access to the reverse proxy config or the Zipline logs, I can't offer much help. If you have access to the containers in the Pterodactyl panel, you may be able to find some info there but other than that I don't know what to suggest.

I have access to my zipline logs but I don't have access to docker logs

**Comment by diced** [comment]
This doesn't seem to be an issue related to Zipline directly, just make sure your DNS records are setup correctly as well as reverse proxies like NGINX. Feel free to reopen this issue if you are having problems or join the discord server.
